### ISSUE TITLE
Changing how many boxes per row

### ISSUE THREAD

**Issue by krish-shahh** [zachsnoek/react-firebase-chat-app#1]
Hi,

I was wondering how I can change the amount of chat room boxes in each row on the home page. Like instead of 2 how can I make it like 4 or 5. 

Thank you

**Comment by zachsnoek** [comment]
Hi @krish-shahh, I'm so sorry for the delayed response.

One thing you could do is adjust the width (i.e., `flex-basis`) of the `.chat-room-list` `li` elements to take up a third of the available space instead of half ([see styles here](https://github.com/zachsnoek/react-firebase-chat-app/blob/main/src/components/Landing/styles.css#L10)). The code would look similar to [this example](https://tobiasahlin.com/blog/common-flexbox-patterns/#3x3-grid-constrained-proportions-169).

If you're looking to understand Flexbox better, I recommend checking out CSS Trick's ["A Complete Guide to Flexbox"](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [Flexbox Froggy](https://flexboxfroggy.com/). A couple of other good resources are [SmolCss](https://smolcss.dev/) and ["Ten modern layouts in one line of CSS."](https://web.dev/one-line-layouts/)

Let me know if you have any other questions!
